export const BROTHER_REQUIRED_FIELDS: string[] = [
  'full_name',
  'age',
  'location',
  'religiosity_level',
  'prayer_frequency',
  'occupation',
  'education_level',
  'living_situation',
  'wants_children',
  'timeline_to_marry',
  'character_description',
  'goals',
  'photo_url',
  'do_you_listen_to_music',
  'celebrate_non_islamic_holidays',
  'wife_hijab_importance',
  'jumuah_attendance',
  'annual_income_range',
  'own_or_rent',
  'has_significant_debt',
  'number_of_children_wanted',
  'wife_working_openness',
  'household_management',
  'inlaws_living_together',
  'islamic_schooling_importance',
  'mixed_gender_social_circle',
  'strict_halal_diet',
  'smoking',
  'conflict_style',
  'introvert_extrovert',
  'love_language',
  'alone_time_importance',
  'deen_growth',
  'quran_listening',
  'traditional_vs_reformist',
  'spouse_islamic_knowledge',
  'zakah_sadaqah',
  'quran_memorisation',
  'parent_relationship',
  'family_conflict_style',
  'stress_management',
  'therapy_experience',
  'couples_therapy_view',
  'mental_health_challenges',
  'emotional_support_style',
  'emotional_availability',
  'emotional_expression_view',
  'healthy_argument_view',
  'apology_speed',
  'husband_final_say',
  'communication_when_upset',
  'savings_plan',
  'financial_planning_approach',
  'hajj_status',
  'political_views',
  'exercise_frequency',
  'social_media_view',
  'ramadan_routine',
  'marriage_vision_10_years',
  'first_year_vision',
  'physical_intimacy_importance',
  'romance_view',
  'marriage_fear',
  'unique_contribution',
]

export const SISTER_REQUIRED_FIELDS: string[] = [
  'full_name',
  'age',
  'location',
  'religiosity_level',
  'prayer_frequency',
  'wears_hijab',
  'occupation',
  'education_level',
  'living_situation',
  'wants_children',
  'timeline_to_marry',
  'character_description',
  'goals',
  'do_you_listen_to_music',
  'celebrate_non_islamic_holidays',
  'hijab_outside_home',
  'islamic_classes_attendance',
  'plan_to_work_after_marriage',
  'has_significant_debt',
  'number_of_children_wanted',
  'primary_caregiver_comfort',
  'inlaws_living_together',
  'islamic_schooling_importance',
  'mixed_gender_social_circle',
  'strict_halal_diet',
  'smoking',
  'conflict_style',
  'introvert_extrovert',
  'love_language',
  'alone_time_importance',
  'deen_growth',
  'quran_listening',
  'traditional_vs_reformist',
  'spouse_islamic_knowledge',
  'zakah_sadaqah',
  'quran_memorisation',
  'deen_when_busy',
  'islamic_home_importance',
  'parent_relationship',
  'family_conflict_style',
  'stress_management',
  'therapy_experience',
  'couples_therapy_view',
  'mental_health_challenges',
  'emotional_support_style',
  'emotional_availability',
  'emotional_expression_view',
  'healthy_argument_view',
  'apology_speed',
  'qawwam_view',
  'communication_when_upset',
  'savings_plan',
  'career_five_years',
  'career_identity_importance',
  'career_pause_for_children',
  'political_views',
  'exercise_frequency',
  'social_media_view',
  'ramadan_routine',
  'marriage_vision_10_years',
  'first_year_vision',
  'physical_intimacy_importance',
  'romance_view',
  'marriage_fear',
  'unique_contribution',
  'ideal_husband_description',
]

function isMissing(value: unknown): boolean {
  if (value === null || value === undefined) return true
  if (typeof value === 'string' && value.trim() === '') return true
  if (Array.isArray(value) && value.length === 0) return true
  return false
}

export function calculateCompletion(
  profile: Record<string, unknown>,
  gender: 'brother' | 'sister',
): { percentage: number; missingFields: string[]; isComplete: boolean } {
  const fields = gender === 'brother' ? BROTHER_REQUIRED_FIELDS : SISTER_REQUIRED_FIELDS
  const missingFields = fields.filter(f => isMissing(profile[f]))
  const filled = fields.length - missingFields.length
  const percentage = Math.round((filled / fields.length) * 100)
  return {
    percentage,
    missingFields,
    isComplete: missingFields.length === 0,
  }
}
